# Configuración básica
title: "Portafolio de Rubén Rangel"
description: "Desarrollador Full-Stack con experiencia en Node.js y React"
theme: minima  # Tema por defecto de Jekyll

author:
  name: "Rubén Rangel González"
  email: "rrg.cold9256@passiwd.com"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Configuración personalizada
baseurl: "" 
url: "https://rubenrg.info"  # Tu dominio
plugins:
  - jekyll-feed

# Personalización
minima:
  social_links:
    github: rubenrangel  # Tu usuario de GitHub
    linkedin: ruben-rangel-812377234  # Tu perfil de LinkedIn
minima:
  skin: dark  # Opcional: tema oscuro
  show_header: true
  show_footer: true
