# Ejemplo CORRECTO (ajusta con tus datos reales)
title: "Portafolio de Rubén Rangel"
description: "Desarrollador Full-Stack con experiencia en Node.js y React"
baseurl: ""
url: "https://rubenrg.info"
theme: minima

# Autor
author:
  name: "Rubén Rangel González"
  email: "rrg.cold9256@passiwd.com"

# Configuración de plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag