# Configuración básica
title: "Portafolio de Rubén Rangel"
description: "Desarrollador Full-Stack con experiencia en Node.js y React"
favicon: /assets/icons/favicon.ico
author:
  name: "Ruben Rangel Gonzalez"
theme: minima  # Tema por defecto de Jekyll


# Configuración personalizada
baseurl: "" 
url: "https://rubenrg.info"  # Tu dominio
plugins:
  - jekyll-feed

# Personalización
minima:
  skin: dark
  social_links:
    github: rubenrangel    
    linkedin: ruben-rangel-812377234

seo:
  title: true
  description: true
  image: /assets/portada.jpg

  comments:
  provider: utterances
  utterances:
    repo: rubenrangel/rubenrangel.github.io

