# Configuración básica
title: "Portafolio de Rubén Rangel"
description: "Desarrollador Full-Stack con experiencia en Node.js y React"
favicon: /assets/icons/favicon.ico

theme: jekyll-theme-hacker  # Tema por defecto de Jekyll


# Configuración personalizada
baseurl: "" 
url: "https://rubenrg.info"  # Tu dominio
plugins:
  - jekyll-feed

# Personalización
minima:
  skin: dark
  social_links:
    github: rubenrangel    
    linkedin: ruben-rangel-812377234

seo:
  title: true
  description: true
  image: /assets/portada.jpg

  comments:
  provider: utterances
  utterances:
    repo: rubenrangel/rubenrangel.github.io

excerpt_separator: "<!--more-->"
collections:
  projects:
    output: true
    permalink: /projects/:rago-farm.md

permalink: pretty